version: '3.7'

services:
  iac:
    container_name: iac
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 4100:4100
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start