apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
spec:
  selector:
    matchLabels:
      app: products
      tier: backend-2
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: products
        tier: backend-2
        track: stable
    spec:
      containers:
      - name: products
        image: myadlapalli/image3
        env: 
          - name: PRODUCT_URL
            value: http://localhost:8082
        ports:
        - containerPort: 9030
apiVersion: v1
kind: Service
metadata:
  name: products
spec:
  selector:
    app: products
    tier: backend-1
  type: NodePort
  ports:
  - protocol: TCP
    port: 9030
    targetPort: 9030
